<a href="https://colab.research.google.com/github/AndriuGJ/Ejercicios/blob/main/Ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EJERCICIO 1

In [2]:
#Mostrar asignaturas en la pantalla y guardarlas
import numpy as np
asignaturas = np.array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'])
np.savetxt('Ejercicio_1.txt', asignaturas, fmt='%s')
print(asignaturas)

['Matemáticas' 'Física' 'Química' 'Historia' 'Lengua']


EJERCICIO 2

In [3]:
#Mostrar asignaturas y mostrar uno aleatoriamente
asignaturas = np.array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'])
mensaje = ("Yo estudio en: ", asignaturas[np.random.randint(5)])
np.savetxt('Ejercicio_2.txt', mensaje, fmt='%s')

EJERCICIO 3

In [4]:
#Mostrar las asignaturas y pedir cuanto saco en cada uno y almacenarlo
asignaturas = np.array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'])
notas= np.array([])
for i in range(5):
  nota = input("¿Qué nota has sacado en " + asignaturas[i] + "?")
  notas = np.append(notas, nota)
np.savetxt('Ejercicio_3.txt', notas, fmt='%s')

¿Qué nota has sacado en Matemáticas?12
¿Qué nota has sacado en Física?18
¿Qué nota has sacado en Química?17
¿Qué nota has sacado en Historia?11
¿Qué nota has sacado en Lengua?20


EJERCICIO 4

In [5]:
1#Pedir numeros y mostralos de menor a menor
num_ganadores = np.array([])
for i in range(3):
  num_ganador = int(input("¿Número ganador? "))
  num_ganadores = np.append(num_ganadores, num_ganador)
  num_ganadores = np.sort(num_ganadores)
print(num_ganadores)
np.savetxt('Ejercicio_4.txt', num_ganadores, fmt='%s')

¿Número ganador? 3
¿Número ganador? 10
¿Número ganador? 2
[ 2.  3. 10.]


EJERCICIO 5

In [6]:
array = np.arange(1, 11)
reverso_array = array[::-1]
print(reverso_array)
np.savetxt('Ejercicio_5.txt', reverso_array, delimiter=",", fmt='%s')

[10  9  8  7  6  5  4  3  2  1]


EJERCICIO 6

In [7]:
asignaturas = np.array(['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua'])
asignaturas_a_repetir = []

for i in range(5):
  nota = int(input("¿Qué nota has sacado en " + asignaturas[i] + "?"))
  if(nota <= 11):
    asignaturas_a_repetir.append(asignaturas[i])

print("Asignaturas a repetir:")
print(asignaturas_a_repetir)
np.savetxt('Ejercicio_6.txt', asignaturas_a_repetir, fmt='%s')

¿Qué nota has sacado en Matemáticas?11
¿Qué nota has sacado en Física?8
¿Qué nota has sacado en Química?5
¿Qué nota has sacado en Historia?10
¿Qué nota has sacado en Lengua?15
Asignaturas a repetir:
[np.str_('Matemáticas'), np.str_('Física'), np.str_('Química'), np.str_('Historia')]


EJERCICIO 7

In [8]:
import string
abecedario = list(string.ascii_lowercase)
abecedario_filtrado = []
for i in range(len(abecedario)):
  if (i + 1) % 3 != 0:
    abecedario_filtrado.append(abecedario[i])
abecedario_filtrado
print(abecedario_filtrado)
np.savetxt('Ejercicio_7.txt', abecedario_filtrado, fmt='%s')

['a', 'b', 'd', 'e', 'g', 'h', 'j', 'k', 'm', 'n', 'p', 'q', 's', 't', 'v', 'w', 'y', 'z']


EJERCICIO 8

In [9]:
palabra = input("Ingresa una palabra para verificar si es un palíndromo: ")
palabra_limpia = palabra.replace(" ", "").lower()
palabra_invertida = palabra_limpia[::-1]
if palabra_limpia == palabra_invertida:
  print(f"'{palabra}' es un palíndromo.")
else:
  print(f"'{palabra}' no es un palíndromo.")
palabra_array = np.array([palabra])
np.savetxt('Ejercicio_8.txt', palabra_array, fmt='%s')

Ingresa una palabra para verificar si es un palíndromo: Ana
'Ana' es un palíndromo.


EJERCICIO 9

In [11]:
#Buscar la cantidad de vocales que tiene una palabra usando numpy as np
palabra = input("Ingresa una palabra: ")
palabra_array = np.array(list(palabra))
vocales = np.array(['a', 'e', 'i', 'o', 'u'])
vocales_encontradas = np.array([])
for i in range(len(palabra_array)):
  for j in range(len(vocales)):
    if palabra_array[i] == vocales[j]:
      vocales_encontradas = np.append(vocales_encontradas, vocales[j])
print(f"La palabra '{palabra}' tiene {len(vocales_encontradas)} vocales.")
np.savetxt('Ejercicio_9.txt', vocales_encontradas, fmt='%s')


Ingresa una palabra: Andriu
La palabra 'Andriu' tiene 2 vocales.


EJERCICIO 10

In [12]:
#Escribir un programa que almacene en una lista los siguientes precios, 50, 75, 46, 22, 80, 65, 8, y
#muestre por pantalla el menor y el mayor de los precios.
precios = np.array([50, 75, 46, 22, 80, 65, 8])
print(f"El precio más barato es {np.min(precios)} y el más caro es {np.max(precios)}.")
np.savetxt('Ejercicio_10.txt', precios, fmt='%s')

El precio más barato es 8 y el más caro es 80.


EJERCICIO 11

In [14]:
#Escribir un programa que almacene los vectores (1,2,3) y (-1,0,2) en dos listas y muestre por
#pantalla su producto escalar.
import numpy as np # Import numpy
vector1 = np.array([1, 2, 3])
vector2 = np.array([-1, 0, 2])
producto_escalar = np.dot(vector1, vector2)
print(f"El producto escalar de los vectores {vector1} y {vector2} es {producto_escalar}.")
np.savetxt('Ejercicio_11.txt', [producto_escalar], fmt='%s') # Save as a 1D array

El producto escalar de los vectores [1 2 3] y [-1  0  2] es 5.


EJERCICIO 12

In [15]:
#Escribir un programa que almacene las matrices en una lista y muestre por pantalla su producto.
#Nota: Para representar matrices mediante listas usar listas anidadas, representando cada vector
#fila en una lista.
matriz1 = np.array([[1, 2, 3], [4, 5, 6]])
matriz2 = np.array([[2, 0], [1, 2], [3, 4]])
producto_matrices = np.dot(matriz1, matriz2)
print(f"El producto de las matrices {matriz1} y {matriz2} es {producto_matrices}.")
np.savetxt('Ejercicio_12.txt', producto_matrices, fmt='%s')

El producto de las matrices [[1 2 3]
 [4 5 6]] y [[2 0]
 [1 2]
 [3 4]] es [[13 16]
 [31 34]].


EJERCICIO 13

In [ ]:
#Escribir un programa que pregunte por una muestra de números, separados por comas, los guarde
#en una lista y muestre por pantalla su media y desviación típica


In [16]:
numeros_str = input("Ingresa una muestra de números separados por comas: ")
numeros_lista = [float(num.strip()) for num in numeros_str.split(',')]
numeros_array = np.array(numeros_lista)

media = np.mean(numeros_array)
desviacion_tipica = np.std(numeros_array)

print(f"La media de los números es: {media}")
print(f"La desviación típica de los números es: {desviacion_tipica}")
np.savetxt('Ejercicio_13.txt', [media, desviacion_tipica], fmt='%s')

Ingresa una muestra de números separados por comas: 1,23,4,5,6,8
La media de los números es: 7.833333333333333
La desviación típica de los números es: 7.104380495315705
